### ISSUE TITLE
Installs OK - error creating new project

### ISSUE THREAD

**Issue by tyeeman** [lsnow99/dudu#2]
Installed in Windows fine. Ran dudu new and this is what I got - 

```
dudu new
?? Dudu  project creator
?? Project name (personal-site): test
2022/08/07 17:07:16 error: mkdir : The system cannot find the path specified.
```
The project directory was created but with no files in it.
Anything come to mind?

**Comment by lsnow99** [comment]
> Installed in Windows fine. Ran dudu new and this is what I got -
> 
> ```
> dudu new
> ?? Dudu  project creator
> ?? Project name (personal-site): test
> 2022/08/07 17:07:16 error: mkdir : The system cannot find the path specified.
> ```
> 
> The project directory was created but with no files in it. Anything come to mind?

Hey! Thanks for filing the issue. It turns out that Go's embed package uses unix path separators even when running on Windows machines. To install the new version with the fix, do `go install -v github.com/lsnow99/dudu/cmd/dudu@v0.1.0`

It made my day to see someone using dudu. Do you mind sharing how you found it? Thanks and let me know if the fix works for you!

**Comment by tyeeman** [comment]
Thanks for the quick answer! I thought it was that problem, I'll try the new version. I found dudu on hacker news last night. I tried searching for it today using github but it didn't come up, hmm.....had to go back to hacker news for the link again!

**Comment by lsnow99** [comment]
> Thanks for the quick answer! I thought it was that problem, I'll try the new version. I found dudu on hacker news last night. I tried searching for it today using github but it didn't come up, hmm.....had to go back to hacker news for the link again!

Interesting, I didn't see the post. Glad you found your way here! Let me know if there's anything else I can do to help.
